name: Build & Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build Live App
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            pm2 stop xl_accounting
            cd /var/www/xl_accounting/live/frontend
            git checkout main
            git reset --hard origin/main
            git pull
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            nvm use 18.17.0
            npm i 
            npm run build
            echo 'Building App'
            pm2 restart xl_accounting
            echo 'Build successful'
